services:
  - type: web
    name: vladtranslogist
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_ADMIN_EMAIL
        value: admin@vladtranslogist.ru
      - key: VITE_ADMIN_PASSWORD
        value: admin123
