services:
  - type: web
    name: vladtranslogist
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_ADMIN_EMAIL
        value: admin@vladtranslogist.ru
      - key: VITE_ADMIN_PASSWORD
        value: admin123
